### ISSUE TITLE
SSL Connection Issues

### ISSUE THREAD

**Issue by Faskis** [samp-incognito/samp-irc-plugin#3]
I posted about this on the support thread but didn't get any response. I've been connecting the plugin through a Slack server and it connects just fine when I set the SSL param to false, but if I try to connect through SSL, it fails saying 'no password' (see below).

> [11/01/2016 16:25:33] **\* IRC_OnConnectAttempt: Bot ID 1 attempting to connect to [slack ip]:6667...
> [11/01/2016 16:25:34] **\* IRC_OnUserRequestCTCP (Bot ID 1): User slackbot (No hostname) sent CTCP request: VERSION
> [11/01/2016 16:25:34] **\* IRC_OnUserSay (Bot ID 1): User slackbot (No hostname) sent message to SAMP: no password
> [11/01/2016 16:25:34] **\* IRC_OnReceiveNumeric (Bot ID 1): 444 (:no password!!!)
> [11/01/2016 16:25:34] **\* IRC_OnDisconnect: Bot ID 1 disconnected from [slack ip]:6667 (End of file)

The password is being properly set in IRC_Connect(), otherwise I don't believe I'd be getting a proper connection when not utilizing SSL. I'm attempting this in a Windows environment but have not tried it in a Linux-based environment (though it will end up being used on CentOS).

**Comment by SysadminJeroen** [comment]
You are probably connecting to a port on the Slack server that is plain text and does not have SSL.

**Comment by Faskis** [comment]
I've attempted the three listed ports (6667, 6697, and 8000) with no success. The only item that Slack lists that's relevant to SSL connections is this:

> If your IRC client has a checkbox to enable SSL, check it! Your IRC connection is not encrypted by default.

It's _possible_ that the issue is on their end as they also state that the IRC gateway is more or less still in beta. I'll drop them an email about this as well just to see if they could help debug this a bit more.

**Comment by SysadminJeroen** [comment]
Try to connect to Freenode or another large IRC network that has SSL.

**Comment by Faskis** [comment]
Connects just fine to freenode through SSL, so it's not an issue with the setup. Seems it may be with Slack specifically, to which I've created a help request with them.

I'd like to keep this issue open in the meantime, in case anyone else here has more to offer or to update on anything Slack says about it.

**Comment by Faskis** [comment]
Just an update since Slack support and I have been having some back and forth, they believe that there may be some compatibility issues between the two. This is what was said in particular:

> "It seems that our gateway simply isn't compatible with this plugin, but if you'd like to send me your config info, I can double-check to make sure you haven't introduced an error."
> 
> ...
> 
> "That all looks good... I'm afraid we simply don't support connections from that client; our gateway support is admittedly particular. Unfortunately, we don't have the game or the server here to test it more thoroughly."

I'd still like to see if we could figure something out on this end, particularly what incompatibility exists when it comes to SSL. Maybe Incognito could provide some insight on the matter?

**Comment by samp-incognito** [comment]
It looks like the password simply isn't sent over SSL connections. Thanks for catching that. I'll fix it in a bit.
