### ISSUE TITLE
1.4.8 (SSL) Failing to Load on Windows

### ISSUE THREAD

**Issue by Faskis** [samp-incognito/samp-irc-plugin#4]
Windows issue: Plugin fails to load (no specific errors). This is all that is shown in the logs:

> [31/01/2016 14:18:09]  Loading plugin: irc.dll
> [31/01/2016 14:18:09]   Failed.
> [31/01/2016 14:18:11] [debug] Run time error 19: "File or function is not found"
> [31/01/2016 14:18:11] [debug]  IRC_Connect
> [31/01/2016 14:18:11] [debug]  IRC_Quit
> [31/01/2016 14:18:11] [debug]  IRC_DestroyGroup
> [31/01/2016 14:18:11] [debug]  IRC_JoinChannel
> [31/01/2016 14:18:11] [debug]  IRC_AddToGroup
> [31/01/2016 14:18:11] [debug]  IRC_SetChannelTopic
> [31/01/2016 14:18:11] [debug]  IRC_RemoveFromGroup
> [31/01/2016 14:18:11] [debug]  IRC_Say
> [31/01/2016 14:18:11] [debug]  IRC_Notice
> [31/01/2016 14:18:11] [debug]  IRC_ReplyCTCP
> [31/01/2016 14:18:11] [debug]  IRC_ChangeNick
> [31/01/2016 14:18:11] [debug] Run time error 19: "File or function is not found"
> [31/01/2016 14:18:11] [debug]  IRC_Connect
> [31/01/2016 14:18:11] [debug]  IRC_Quit
> [31/01/2016 14:18:11] [debug]  IRC_DestroyGroup
> [31/01/2016 14:18:11] [debug]  IRC_JoinChannel
> [31/01/2016 14:18:11] [debug]  IRC_AddToGroup
> [31/01/2016 14:18:11] [debug]  IRC_SetChannelTopic
> [31/01/2016 14:18:11] [debug]  IRC_RemoveFromGroup
> [31/01/2016 14:18:11] [debug]  IRC_Say
> [31/01/2016 14:18:11] [debug]  IRC_Notice
> [31/01/2016 14:18:11] [debug]  IRC_ReplyCTCP
> [31/01/2016 14:18:11] [debug]  IRC_ChangeNick
> [31/01/2016 14:18:11] Script[gamemodes]: Run time error 19: "File or function is not found"

Plugin and include were both updated, along with the script being recompiled.

**Comment by Faskis** [comment]
Also, on the Linux version, half of the callbacks don't seem to be getting ran, including: OnUserRequestCTCP, OnConnect, OnUserSetChannelTopic, and OnUserSay. They work fine on 1.4.7. Possibly related to the Windows issue?

**Comment by samp-incognito** [comment]
1.4.8 was compiled with VS 2015, so you'll need to install .NET 4.6.1 if you want to run it on Windows.

As for the Linux version, it seems to work fine for me. Is it loading properly? You might have to compile it yourself.

**Comment by Faskis** [comment]
I'm running Windows 10 and have confirmed that .NET Framework 4.6.1 is installed, so I don't think that's the issue. I can try to compile that from source later and see if it makes any difference.

As for the Linux version, the callbacks work fine when running a non-SSL connection, but stop working once SSL is enabled. I can also try compiling this later.

**Comment by samp-incognito** [comment]
Do you have the Visual C++ 2015 Redistributable installed as well? (You don't need .NET, actually, though I thought at one time the .NET installer also installed the VC++ redistributables... perhaps not.) Keep in mind you'll also need to have the OpenSSL binaries installed.

Do you mean the Linux version works for you when you connect to a non-SSL server while running the SSL version of the plugin, or does it only work while running the non-SSL version of the plugin? Is anything passed to `IRC_OnReceiveRaw`?

**Comment by Faskis** [comment]
Okay, the Windows issue was because I didn't have the 32-bit version of the Visual C++ 2015 Redistrubutable. Everything is working on there now.

As for the Linux version, this is on the SSL version of the plugin, but attempting the connection through SSL and without. When SSL is enabled, it runs into problems. Without SSL enabled, it works fine.

**Comment by samp-incognito** [comment]
Updates on this? I just ran the Linux SSL version and connected to an SSL server, so this must something on your end. I think you may just need to compile the plugin yourself (or ask someone to do it for you) if you're still having trouble.
