### ISSUE TITLE
Extended BNC / Server support

### ISSUE THREAD

**Issue by karimcambridge** [samp-incognito/samp-irc-plugin#5]
The only feature I see lacking is better BNC support. I've changed my bots from connecting each time to connecting to a server (BNC).

I was wondering if these things we're possible.

On BNC connection:

Request channels that are already in (IRC_IsBotInChannel);
Request identification information (IRC_IsBotIndentified);
Request user modes (IRC_GetMode).

I know your very busy atm, but is it possible? I'll look into doing it myself.

**Comment by samp-incognito** [comment]
I suppose that information could persist in the plugin even after the bot disconnects, though it would probably have to be manually entered by the user on startup. I don't think there would be a way of automatically querying the BNC since the method for doing so differs by implementation.
